version: "3"
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 4000:4000
    environment:
      PORT: 4000
      LOG_LEVEL: info
      NODE_ENV: development
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      
  db:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - ./docker/db/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
