version: "3"
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - 4000:4000
    env_file:
      - .env
    environment:
      PORT: 4000
      LOG_LEVEL: info
      NODE_ENV: development
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: db
      DB_PORT: $DB_PORT
    command: npm run start
      
  db:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    env_file: 
        - .env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
